### ISSUE TITLE
io-ts v3 vs morphic-ts

### ISSUE THREAD

**Issue by anilanar** [sledorze/morphic-ts#73]
How does `morphic-ts` relate to https://github.com/gcanti/io-ts/pull/440?

**Comment by sledorze** [comment]
Hi @anilanar, thanks for the question.

The goals are not the same:

From my experience:

Io-ts is a decoding / encoding library
Many users (including myself) were wanting to define other aspects of their models from their io-ts definitions, using tag based matching.
Io-ts being extensible and so, open, this was a brittle solution as un-handling of specific cases would result result in runtime errors.

The next iteration of `io-ts` will rely on Schemable to ease deriving specific type classes thanks to the final tagless pattern.

`Morphic` is also relying on the final tagless pattern, however, the library goals is to provide a complete solution for business modeling.

Some differences:

- Iots provides Schemable for Kind1, Morphic provides Algebra for Kind1 & Kind2 (the pattern could allow more).
- Customisation:
	- Iots Schemable: by extending Schemable and providing new implementations.
	- Morphic: by creating new Algebras, providing new implementations (on need) or specifying/overriding via Configs.

Also with Morphic, you also get builders, matchers, reducers, predicates, optics for free etc.. also the Api is done so that with a required but minimal boilerplate per definition, one can benefit from Opaque, meaningful types everywhere.

(There's a whole work on Config Envs that will be out shortly to increase Configs capabilities)

Those days, Morphic is using classic io-ts under the hood for encoding / decoding; we may switch to the next io-ts v3, however, doing so we may loose the `Output` type and from some users, that would be a problem because they're relying on it.

**Comment by anilanar** [comment]
Thanks for the good summary ❤️
